package project

class BootStrap {

    def init = { servletContext ->

        Users u1=new Users(username : 'nitin' , fName :'nitin'  , lName : 'nepalia' , password : 'nitin' , admin : false , active : true , email : 'nitin@gmail.com' )
        Users u2=new Users(username : 'saurabh' , fName :'saurabh'  , lName : 'kumar' , password : 'saurabh' , admin : false , active : true , email : 'saurabh@gmail.com')
        Users u3=new Users(username : 'aman' , fName :'aman'  , lName : 'aggarwal' , password : 'aman' , admin : false , active : true , email : 'aman@gmail.com')
        Users u4=new Users(username : 'rishabh' , fName :'rishabh'  , lName : 'gupta' , password : 'rishabh' , admin : true , active : true , email : 'rishabh@gmail.com')
/*        Topic t1=new Topic()
        Topic t2=new Topic()
        Topic t3=new Topic()
        Resources r1=new Resources()
        Resources r2=new Resources()
        Resources r3=new Resources()*/
        // print"cssssssssssssssssssssssssssssssssssssd"
        u1.save(flush:true,failOnError:true)
        Topic topic1 = new Topic(name:"html",visibility: "PUBLIC")
        Topic topic2 = new Topic(name:"css",visibility: "PUBLIC")
        Topic topic3 = new Topic(name:"javascript",visibility: "PUBLIC")
        Topic topic11 = new Topic(name:"groovy",visibility: "PRIVATE")
        Topic topic12 = new Topic(name:"grails",visibility: "PRIVATE")
        u4.addToTopics1(topic1)
        u4.addToTopics1(topic2)
        u4.save(flush:true,failOnError: true)
        topic1.save(flush:true,failOnError: true)
        topic2.save(flush:true,failOnError: true)
        u3.addToTopics1(topic3)
        u3.addToTopics1(topic11)
        u3.save(flush:true,failOnError: true)
        topic3.save(flush:true,failOnError: true)
        topic11.save(flush:true,failOnError: true)
        u2.addToTopics1(topic12)
        u2.save(flush:true,failOnError: true)
        topic12.save(flush:true,failOnError: true)
        //u4.save()
        Resources resource1 = new Resources(description:"This is first Post",topic:topic1)
        Resources resource2 = new Resources(description:"This is second Post",topic:topic1)
        Resources resource3 = new Resources(description:"This is third Post",topic:topic2)
        Resources resource4 = new Resources(description:"This is fourth Post",topic:topic3)
        u4.addToResources1(resource1)
        //user1.save(flush:true,failOnError: true)
        u4.addToResources1(resource2)
        //user1.save(flush:true,failOnError: true)
        u4.addToResources1(resource3)
        u4.save(flush:true,failOnError: true)
        //user2.save(flush:true,failOnError: true)
        u3.addToResources1(resource4)
        u3.save(flush:true,failOnError: true)
        //user2.save(flush:true,failOnError: true)
        topic1.addToResources2(resource1)
        //topic1.save(flush:true,failOnError:true)
        topic1.addToResources2(resource2)
        topic1.save(flush:true,failOnError: true)
        //topic1.save(flush:true,failOnError:true)
        topic2.addToResources2(resource3)
        topic2.save(flush:true,failOnError: true)
        //topic2.save(flush:true,failOnError:true)
        topic3.addToResources2(resource4)
        topic3.save(flush:true,failOnError: true)
        resource1.save(flush:true,failOnError:true)
        resource2.save(flush:true,failOnError:true)
        resource3.save(flush:true,failOnError:true)
        resource4.save(flush:true,failOnError:true)
        Subscription s1=new Subscription(seriousness: "CASUAL" ,topic :topic1)
        Subscription s2=new Subscription(seriousness: "CASUAL" , topic : topic2)
        Subscription s3=new Subscription(seriousness: "CASUAL" , topic : topic3)
        Subscription s4=new Subscription(seriousness: "CASUAL" , topic : topic11)
        Subscription s5=new Subscription(seriousness: "CASUAL" , topic: topic12)
        Subscription subs=new Subscription(seriousness: "CASUAL" ,topic:topic11)
        Subscription sub=new Subscription(seriousness: "CASUAL" , topic :topic1)
        Subscription su=new Subscription(seriousness: "CASUAL" , topic :topic2)
        u4.addToSubscribed(s1)
        u4.addToSubscribed(s2)
        u4.addToSubscribed(subs)
        u3.addToSubscribed(s3)
        u3.addToSubscribed(s4)
        u2.addToSubscribed(s5)
        u1.addToSubscribed(sub)
        u1.addToSubscribed(su)
        topic1.addToSubscriptions1(s1)
        topic1.addToSubscriptions1(sub)
        topic2.addToSubscriptions1(su)
        topic2.addToSubscriptions1(s2)
        topic3.addToSubscriptions1(s3)
        topic11.addToSubscriptions1(s4)
        topic11.addToSubscriptions1(subs)
        topic12.addToSubscriptions1(s5)

        s1.save(flush:true,failOnError:true)
        s2.save(flush:true,failOnError:true)
        s3.save(flush:true,failOnError:true)
        s4.save(flush:true,failOnError:true)
        s5.save(flush:true,failOnError:true)
        subs.save(flush:true,failOnError:true)
        sub.save(flush:true,failOnError:true)
        su.save(flush:true,failOnError:true)

    }
    def destroy = {
    }
}
